version: 2
updates:
  # Backend Lambdas
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  # Frontend Next.js
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  # Admin Vue
  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions:
        patterns: ["*"]
