formatter: markdown table

sections:
  hide:
    - providers

content: |-
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject

settings:
  indent: 2
  lockfile: false
