//
// Serves responsive images transparently:
// - Extensionless base path (new format): renders <picture> with AVIF + WebP in 3 sizes.
//   Browser automatically picks the best format + size for the viewport.
// - `lqip` prop: inline data URI (e.g. "data:image/webp;base64,...") used as
//   background-image blur placeholder while the real image loads. Zero
//   extra HTTP request, no risk of 403 for posts without a generated lqip.

interface ResponsiveImageProps {
  src: string;
  alt: string;
  fill?: boolean;
  priority?: boolean;
  sizes?: string;
  className?: string;
  lqip?: string; // inline data URI of the blur placeholder (imagem_lqip_base64)
}

/**
 * Normalizes src to an extensionless basePath.
 * URLs from the old admin arrive with .webp/.jpg appended (e.g. media/uuid.webp),
 * but imageProcessor generates variants like media/uuid-480.avif.
 * Stripping the extension lets <picture> build the correct variant URLs.
 */
function toBasePath(src: string): string {
  return src.replace(/\.(webp|avif|jpg|jpeg|png|gif)(\?.*)?$/i, '');
}

export default function ResponsiveImage({
  src,
  alt,
  fill = false,
  priority = false,
  sizes,
  className,
  lqip,
}: ResponsiveImageProps) {
  if (!src) return null;

  const basePath = toBasePath(src);

  // Variants generated by imageProcessor:
  //   {basePath}-480.avif  |  {basePath}-480.webp
  //   {basePath}-768.avif  |  {basePath}-768.webp
  //   {basePath}-1280.avif |  {basePath}-1280.webp

  const imgProps: React.ImgHTMLAttributes<HTMLImageElement> & { fetchPriority?: string } = {
    src: `${basePath}-1280.webp`,
    alt,
    loading: priority ? "eager" : "lazy",
    fetchPriority: priority ? "high" : "auto",
    decoding: "async",
    style: fill
      ? { width: "100%", height: "100%", objectFit: "cover", display: "block" }
      : undefined,
    sizes,
    className,
  };

  if (fill) {
    return (
      <picture
        style={{
          display: "block",
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          // lqip is an inline data URI, zero HTTP request, zero risk of 403.
          // Absent: no background (silent degradation for posts without lqip).
          ...(lqip && {
            backgroundImage: `url(${lqip})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }),
        }}
      >
        <source media="(max-width: 480px)" type="image/avif" srcSet={`${basePath}-480.avif`} />
        <source media="(max-width: 480px)" type="image/webp" srcSet={`${basePath}-480.webp`} />
        <source media="(max-width: 768px)" type="image/avif" srcSet={`${basePath}-768.avif`} />
        <source media="(max-width: 768px)" type="image/webp" srcSet={`${basePath}-768.webp`} />
        <source type="image/avif" srcSet={`${basePath}-1280.avif`} />
        <img {...imgProps} alt={alt} />
      </picture>
    );
  }

  return (
    <picture>
      <source media="(max-width: 480px)" type="image/avif" srcSet={`${basePath}-480.avif`} />
      <source media="(max-width: 480px)" type="image/webp" srcSet={`${basePath}-480.webp`} />
      <source media="(max-width: 768px)" type="image/avif" srcSet={`${basePath}-768.avif`} />
      <source media="(max-width: 768px)" type="image/webp" srcSet={`${basePath}-768.webp`} />
      <source type="image/avif" srcSet={`${basePath}-1280.avif`} />
      <img {...imgProps} alt={alt} />
    </picture>
  );
}
